# fly.toml app configuration file generated for htb-2026 on 2026-03-15T02:07:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'htb-2026'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
